site_name: GestVenv Documentation
site_url: https://thearchit3ct.github.io/gestvenv/
repo_url: https://github.com/thearchit3ct/gestvenv
repo_name: thearchit3ct/gestvenv
edit_uri: edit/main/docs/

# Configuration pour GitHub Pages
use_directory_urls: true

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: fr
  # - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Accueil: index.md
  - Installation: getting-started/installation.md
  - Guide Utilisateur: 
    - Démarrage rapide: getting-started/first-environment.md
    - Commandes de base: getting-started/basic-commands.md
    # - installation: getting-started/installation.md
  - Guide Développeur:
    # - developer-guide/index.md
    - Architecture: developer-guide/architecture.md
    - Contribution: developer-guide/contributing.md
    - api: developer-guide/api.md
    - code-structure: developer-guide/code-structure.md
  # - Référence API:
  #   - api/index.md
  #   - Core: api/core.md
  #   - Services: api/services.md
  #   - Utilitaires: api/utils.md
  # - Exemples:
  #   - examples/index.md
  #   - Utilisation basique: examples/basic-usage.md
  #   - Projets avancés: examples/advanced-projects.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thearchit3ct/gestvenv
  version:
    provider: mike