# Configuration MkDocs pour GestVenv
site_name: GestVenv - Gestionnaire d'Environnements Virtuels Python
site_description: Documentation complète pour GestVenv, un outil de gestion d'environnements virtuels Python
site_author: thearchit3ct
site_url: https://thearchit3ct.github.io/gestvenv

# Dépôt
repo_name: thearchit3ct/gestvenv
repo_url: https://github.com/thearchit3ct/gestvenv
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: fr
  palette:
    # Mode clair
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Basculer vers le mode sombre
    # Mode sombre
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Basculer vers le mode clair
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.tooltips
    - toc.follow
    - toc.integrate
  
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Navigation
nav:
  - Accueil: index.md
  - Guide de démarrage:
    - Installation: getting-started/installation.md
    - Premier environnement: getting-started/first-environment.md
    - Commandes de base: getting-started/basic-commands.md
  - Guide utilisateur:
    - Gestion des environnements: user-guide/environment-management.md
    - Gestion des packages: user-guide/package-management.md
    - Import et Export: user-guide/import-export.md
    - Configuration: user-guide/configuration.md
    - Workflows recommandés: user-guide/workflows.md
  - Référence CLI:
    - Vue d'ensemble: cli-reference/overview.md
    - Commandes create/delete: cli-reference/environment-commands.md
    - Commandes packages: cli-reference/package-commands.md
    - Commandes utilitaires: cli-reference/utility-commands.md
    - Options globales: cli-reference/global-options.md
  - Guide développeur:
    - Architecture: developer-guide/architecture.md
    - Structure du code: developer-guide/code-structure.md
    - Tests: developer-guide/testing.md
    - Contribution: developer-guide/contributing.md
    - API interne: developer-guide/api.md
  - Avancé:
    - Intégration CI/CD: advanced/ci-cd.md
    - Scripting: advanced/scripting.md
    - Personnalisation: advanced/customization.md
    - Dépannage: advanced/troubleshooting.md
  - Exemples:
    - Projets web: examples/web-projects.md
    - Data science: examples/data-science.md
    - DevOps: examples/devops.md
    - Équipes: examples/team-workflows.md
  - FAQ: faq.md
  - Changelog: changelog.md

# Plugins
plugins:
  - search:
      lang: fr
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - minify:
      minify_html: true
  # - macros:
  #     module_name: docs/macros
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            heading_level: 2

# Extensions Markdown
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: thearchit3ct
      repo: gestvenv
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Configuration supplémentaire
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thearchit3ct/gestvenv
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/gestvenv/
  generator: false
  analytics:
    feedback:
      title: Cette page vous a-t-elle été utile ?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Cette page m'a aidé
          data: 1
          note: >-
            Merci pour votre retour !
        - icon: material/emoticon-sad-outline
          name: Cette page pourrait être améliorée
          data: 0
          note: >-
            Merci pour votre retour ! Aidez-nous à améliorer cette page en
            <a href="https://github.com/thearchit3ct/gestvenv/issues/new/?title=[Docs]%20{title}%20-%20{url}" target="_blank" rel="noopener">créant une issue</a>.

# CSS et JavaScript personnalisés
extra_css:
  - stylesheets/extra.css
  - stylesheets/termynal.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/termynal.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Configuration du copyright
copyright: >
  Copyright &copy; 2025 thearchit3ct –
  <a href="#__consent">Modifier les paramètres de cookies</a>

# Variables de validation
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn

# Configuration de build
strict: true
use_directory_urls: true

# Répertoires
docs_dir: docs
site_dir: site

# Fichiers à exclure
exclude_docs: |
  *.tmp
  *.bak
  *~